spring:
  datasource:
    username: root
    password: Aabc123456789
    url: jdbc:mysql://localhost:3306/cymmtj?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    root: info
    com.gouzhong1223.blog.controller: info
    com.gouzhong1223.blog.service: info
    com.gouzhong1223.blog.mapper: info
    com.lucifer.springboot.cache.mapper: debug
  path: log/blog.log
  file:
    max-size: 10MB
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
oss:
  endpoint: oss-cn-shanghai.aliyuncs.com
  keyid: 去OSS控制台获取
  keysecret: 去OSS控制台获取
  bucketname: java4all-file
  filehost: blog

